package com.garganttua.events.spec.interfaces.context;

import com.garganttua.events.context.GGEventsContextDataflowInProcessMode;
import com.garganttua.events.context.GGEventsContextDestinationPolicy;
import com.garganttua.events.context.GGEventsContextHighAvailabilityMode;
import com.garganttua.events.context.GGEventsContextOriginPolicy;

public interface IGGEventsContextSubscription extends IGGEventsContextItemLinkedToContext {

	IGGEventsContextSubscription producerConfiguration(GGEventsContextDestinationPolicy destinationPolicy,
			String destinationUuid);

	IGGEventsContextSubscription consumerConfiguration(GGEventsContextDataflowInProcessMode inProcessMode,
			GGEventsContextOriginPolicy originPolicy, GGEventsContextDestinationPolicy destinationPolicy,
			boolean ignoreAssetMessages, GGEventsContextHighAvailabilityMode haMode);
	
	IGGEventsContextSubscription producerConfiguration(IGGEventsContextProducerConfiguration configuration);

	IGGEventsContextSubscription consumerConfiguration(IGGEventsContextConsumerConfiguration configuration);

}
